package integration
 
import transfer.*;
import transfer.datacenter.*;
import transfer.visudesign.*;
import transfer.association.*;
import services.auxiliary.*;
import services.domains.*;
import services.accesspoint.*;

import VisualizationDesignService.domain.*;

import message.CharacterizeVisuMsg;
import message.DeclareDashboardMsg;
import message.PlugDataMsg;
import message.DeclareCatalogMsg;
import message.IsDefinedMsg;
import message.IsDefinedAsw;

/****** Integration Rules *******/

/* Plug Data */

rule "Plug Data - No Catalog linked"
    when
        $msg : PlugDataMsg ( $dashboard : dashboardName) and
        $ans: GetLinkedAsw (model == null) from Association.getLinked(new GetLinkedMsg($dashboard))        
    then
    	System.out.println("Rule \"Plug Data - No Catalog\" triggered !");
end

rule "Plug Data - Resource matching Data"
    when
        $msg : PlugDataMsg ( $dashboard : dashboardName, $uri : dataName) and
        GetLinkedAsw ($catalog : model != null) from Association.getLinked(new GetLinkedMsg($dashboard)) and
        IsDefinedAsw (defined == true) from SensorDeploymentDomain.isDefined(new IsDefinedMsg($catalog, $uri))
    then
    	System.out.println("Rule \"Plug Data - Resource matching Data\" triggered !");
end

rule "Plug Data - No Resource matching Data"
    when
        $msg : PlugDataMsg ( $dashboard : dashboardName, $uri : dataName) and
        GetLinkedAsw ($catalog : model != null) from Association.getLinked(new GetLinkedMsg($dashboard))
        IsDefinedAsw (defined == false) from SensorDeploymentDomain.isDefined(new IsDefinedMsg($catalog, $uri))
    then
    	System.out.println("Rule \"Plug Data - No Resource matching Data\" triggered !");
end

/* Characterize 

rule "Characterize - Threshold - No Catalog"
    when
        $msg : CharacterizeVisuMsg ( $dashboard : dashboardName, $concernsMap : whatQualifier, $concernsMap.containsKey("Threshold") ) and
        $ans: GetLinkedAsw (model == null) from Association.getLinked(new GetLinkedMsg($dashboard))        
    then
    	System.out.println("Rule \"Characterize - Threshold - No Catalog\" triggered !");
    	//TODO Log : no integration
end

rule "Characterize - Threshold - One Catalog"
    when
        $msg : CharacterizeMsg ( $dashboard : dashboardName, $concernsMap : concerns, $concernsMap.containsKey("Threshold") ) and
        GetLinkedAsw ($catalog : model != null) from Association.getLinked(new GetLinkedMsg($dashboard))
        
    then
    	System.out.println("Rule \"Characterize - Threshold - One Catalog\" triggered !");
end


rule "Characterize - Threshold - Several Catalog"
    when
        $msg : CharacterizeMsg ( $dashboard : dashboardName, $concernsMap : concerns, $concernsMap.containsKey("Threshold") ) and
        $ans: GetLinkedAsw (model == null) from Association.getLinked(new GetLinkedMsg($dashboard))        
    then
    	System.out.println("Rule \"Characterize - Threshold - Several Catalog\" triggered !");
end
*/

/****** Routing Rules ******/

rule "Link"
	when
		$msg : LinkMsg( )
	then
    	System.out.println("Rule Link triggered !");
		Association.link($msg);
end

/*
rule "Test"
	when
		$service : VisualizationDesign()
	then
    	System.out.println("Test rule triggered !");
end
*/	

rule "Declare Dashboard"
	when
		$msg : DeclareDashboardMsg()
	then
    	System.out.println("Rule Declare Dashboard triggered !");
		VisualizationDesignAP.declareDashboard($msg);
end

rule "Characterize Visualization"
	when
		$msg : CharacterizeVisuMsg()
	then
    	System.out.println("Rule Add Visualization triggered !");
		VisualizationDesignDomain.characterizeVisu($msg);
end

rule "Declare Catalog"
	when
		$msg : DeclareCatalogMsg()
	then
    	System.out.println("Rule Declare Catalog triggered !");
		SensorDeploymentDomain.declareCatalog($msg);
end
