package integration
 
import transfer.*;
import transfer.datacenter.*;
import transfer.visudesign.*;
import transfer.association.*;
import services.auxiliary.*;
import services.domains.*

/****** Integration Rules *******/

/* Plug Data */

rule "Plug Data - No Catalog linked"
    when
        $msg : PlugDataMsg ( $dashboard : dashboardName) and
        $ans: GetLinkedAsw (model == null) from Association.getLinked(new GetLinkedMsg($dashboard))        
    then
    	System.out.println("Rule \"Plug Data - No Catalog\" triggered !");
    	//TODO Log : no integration
end

rule "Plug Data - Resource matching Data"
    when
        $msg : PlugDataMsg ( $dashboard : dashboardName, $uri : uri) and
        GetLinkedAsw ($catalog : model != null) from Association.getLinked(new GetLinkedMsg($dashboard)) and
        IsDefinedAsw (answer == true) from DataCenter.isDefined(new IsDefinedMsg($catalog, $uri))
    then
    	System.out.println("Rule \"Plug Data - Resource matching Data\" triggered !");
end

rule "Plug Data - No Resource matching Data"
    when
        $msg : PlugDataMsg ( $dashboard : dashboardName, $uri : uri) and
        GetLinkedAsw ($catalog : model != null) from Association.getLinked(new GetLinkedMsg($dashboard))
        IsDefinedAsw (answer == false) from DataCenter.isDefined(new IsDefinedMsg($catalog, $uri))
    then
    	System.out.println("Rule \"Plug Data - No Resource matching Data\" triggered !");
end

/* Characterize */

rule "Characterize - Threshold - No Catalog"
    when
        $msg : CharacterizeMsg ( $dashboard : dashboardName, $concernsMap : concerns, $concernsMap.containsKey("Threshold") ) and
        $ans: GetLinkedAsw (model == null) from Association.getLinked(new GetLinkedMsg($dashboard))        
    then
    	System.out.println("Rule \"Characterize - Threshold - No Catalog\" triggered !");
    	//TODO Log : no integration
end

rule "Characterize - Threshold - One Catalog"
    when
        $msg : CharacterizeMsg ( $dashboard : dashboardName, $concernsMap : concerns, $concernsMap.containsKey("Threshold") ) and
        GetLinkedAsw ($catalog : model != null) from Association.getLinked(new GetLinkedMsg($dashboard))
        
    then
    	System.out.println("Rule \"Characterize - Threshold - One Catalog\" triggered !");
end

/*
rule "Characterize - Threshold - Several Catalog"
    when
        $msg : CharacterizeMsg ( $dashboard : dashboardName, $concernsMap : concerns, $concernsMap.containsKey("Threshold") ) and
        $ans: GetLinkedAsw (model == null) from Association.getLinked(new GetLinkedMsg($dashboard))        
    then
    	System.out.println("Rule \"Characterize - Threshold - Several Catalog\" triggered !");
end
*/

/****** Routing Rules ******/

rule "Link"
	when
		$msg : LinkMsg( )
	then
    	System.out.println("Rule Link triggered !");
		Association.link($msg);
end